Support negative lat/long
cheeaun/nobita pull request #1
Opened 2018-01-28 14:55 UTC by mattburman

2018-01-31 01:02 UTC, cheeaun requested changes

2018-01-31 01:02 UTC, cheeaun commented on index.js
> +  const [lat, lng, accuracy] = stdout.split('\n').filter((line) => /(lat|long|accuracy)/i.test(line)).map((line) => line.match(/-[\d\.]+/)[0]);
Feels like the regex here should be `/[-\d\.]+/` instead, to match both positive and negative lat/long :)

2018-02-04 15:58 UTC, mattburman commented
Good catch, thanks! 🙌

2018-02-04 16:18 UTC, cheeaun approved these changes

2018-02-04 16:18 UTC, merged